swagger: '2.0'
info:
  description: This is a simple API
  version: 1.0.0
  title: Car Pooling API
  # put the contact info for your development or API team
  contact:
    email: you@your-company.com

  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html

# tags are used for organizing operations
tags:
- name: customers
  description: Customer submitted requests
- name: drivers and management
  description: Reports submitted by drivers

paths:
  /request:
    post:
      tags:
      - customers
      summary: requests a ride
      operationId: app.rideRequest
      description: Submits a request for a ride
      consumes:
      - application/json
      produces:
      - application/json
      parameters:
      - in: body
        name: requestInfo
        description: Ride request submission
        schema:
          $ref: '#/definitions/RequestInfo'
      responses:
        201:
          description: request submitted
        400:
          description: invalid input, object invalid
        409:
          description: an existing item already exists
  /report:
    post:
      tags:
      - drivers and management
      summary: submits the ride report
      operationId: app.rideReport
      description: submits the report to the system
      consumes:
      - application/json
      produces:
      - application/json
      parameters:
      - in: body
        name: reportInfo
        description: report item to add
        schema:
          $ref: '#/definitions/ReportInfo'
      responses:
        201:
          description: report created
        400:
          description: invalid input, object invalid
        409:
          description: an existing item already exists

definitions:
  RequestInfo:
    type: object
    required:
    - name
    - location
    - destination
    - time
    - notes
    properties:
      name:
        type: string
        example: Mike Tyson
      location:
        type: string
        example: 12354 101b Avenue
      destination:
        type: string
        example: McDonalds, 223rd St
      time:
        type: string
        example: '15:00'
      notes:
        type: string
        example: The house with the blue mailbox
  ReportInfo:
    type: object
    required:
    - name
    - customer
    - pickup
    - dropoff
    - pickuptime
    - dropofftime
    - rating
    - notes
    properties:
      name:
        type: string
        example: Driver Driverson
      customer:
        type: string
        example: Geddy Lee
      pickup:
        type: string
        example: 2240 122nd St
      dropoff:
        type: string
        example: Chuck-e-Cheese, 278th St
      pickuptime:
        type: string
        example: '13:30'
      dropofftime:
        type: string
        example: '14:15'
      rating:
        type: string
        example: '4/5'
      notes:
        type: string
        example: 'Polite and considerate customer'

